lib: 'hippocampus/commonwords'
records: 'hippocampus/acro'
minlen: 4
maxlen: 5
rounds: 2

roundtime: 30
warning: 30
votetime: 30
rest: 5

minplayers: 1
timefactor: 2
noacropenalty: 2
novotepenalty: 5
botplay: True

insults:
  - 'are little bitches'
  - 'are chumps'
  - 'are cunt knockers'
  - 'are lazy bastards'

insult:
  - 'is a little bitch'
  - 'is a chump'
  - 'is a cunt knocker'
  - 'is a lazy bastard'
