url: 'http://www.mongobot.com/diplomacy'

countries:
  Austria:
    color: 'red'
    positions:
      Vienna: 'A'
      Budapest: 'A'
      Trieste: 'F'
  England:
    color: 'blue'
    positions:
      Liverpool: 'A'
      London: 'F'
      Edinburgh: 'F'
  France:
    color: 'pink'
    positions:
      Paris: 'A'
      Marseilles: 'A'
      Brest: 'F'
  Germany:
    color: 'black'
    positions:
      Berlin: 'A'
      Munich: 'A'
      Kiel: 'F'
  Italy:
    color: 'green'
    positions:
      Rome: 'A'
      Venice: 'A'
      Naples: 'F'
  Russia:
    color: 'white'
    positions:
      Moscow: 'A'
      Warsaw: 'A'
      Sevastopol: 'F'
      St_Petersburg: 'F'
  Turkey:
    color: 'yellow'
    positions:
      Constantinople: 'A'
      Smyrna: 'A'
      Ankasa: 'F'

