#
# IRC Connection settings
#

enabled: true
module: 'MongoBot.thalami.IRC.IRC'

settings:
    ident: 'foobard'
    realname: 'foobard'
    nick: 'foobard'
    host: 'chat.freenode.net'
    password: !env IRC_PASSWORD
    port: 6697
    ssl: True
    chanserv: False
    channels:
     - '#fubahder'

