version: 1
disable_existing_loggers: true

root:
  level: !!python/name:logging.NOTSET
  handlers: [console]

loggers:
  info:
    level: !!python/name:logging.INFO
    handlers: [console]
    qualname: info
    propagate: false
  debug:
    level: !!python/name:logging.DEBUG
    handlers: [logfile]
    qualname: debug
    propagate: false
  warn:
    level: !!python/name:logging.WARN
    handlers: [console, logfile]
    qualname: warn
    propagate: false

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simple
    level: !!python/name:logging.NOTSET
  logfile:
    class: logging.FileHandler
    filename: sample.log
    formatter: extended
    level: !!python/name:logging.NOTSET

formatters:
  simple:
    class: !!python/name:logging.Formatter
    format: '%(message)s'
    datefmt: ' '
  extended:
    class: !!python/name:logging.Formatter
    format: '%(asctime)s %(levelname)s %(message)s'
    datefmt: '%d/%m/%Y %H:%M:%S'

