plugins:
  - acro
  - alien
  - artsy
  - broca
  - channeling
  - chess
  - facebook
  - farkle
  - finance
  - hangman
  - holdem
  - linker
  - marvel
  - memory
  - nonsense
  - peeps
  - polling
  - quotes
  - reference
  - sms
  - stockgame
  - system
  - tester
  - turing
  - twitting
  - webserver
