# --------------------- Core secrets

owner: your_nick

primary_channel: '#your_channel'

bot:
  ident: ''
  realname: ''
  password: Null # The password to the IRC server

irc:
  password: False

channels:
  '#your_channel':
    primary: True # may be superfluous with primary_channel
    mods:
      - 'command'
      - 'speak'
    history: |
      If you want a kind of room history, put it here for the history command

# --------------------- Brainmeat autoloaded secrets

system:
  botpass: 'password' 

# For use with twilio
sms:
  lockfile: '/tmp/sms.lock'
  sid: ''
  token: ''
  number: ''
  # Allows commands to be sent from these numbers
  bypass:
    - '1234567890'


# My personal standard practice for
# setting up a new web presence is
# to setup a google account and base
# all the other accounts off that,
# hence the automatic inclusion of 
# the google account as the user
# for other applications. -HW

mail:
  user: ''
  email: 'something@gmail.com'
  password: ''

facebook:
  user: ""
  pass: ''
  page: ''
  appid: ''
  secret: ''

twitting:
  user: ""
  password: ''
  consumerkey: ''
  consumersecret: ''
  accesstoken: ''
  accesssecret: ''

broca:
  wordnik_api: ''

nonsense:
  fml_api: ''

reference:
  wolfram_api: ''
  weather_api: ''

peeps:
  meetup:
    location: 'This can be any description'
    notify: [12, 17] # notifies at noon and 5pm the day of
    day: '2nd Tuesday' # This is NOT arbitrary; it will notify on the 2nd Tuesday or 3rd Friday, etc.

marvel:
  publickey: ''
  privatekey: ''

github:
  clientid: ''
  clientsecret: ''
  token: ''

alien:
  appid: ''
  secret: ''

webserver:
  user: ''
  password: ''

civics:
  openstatekey: ''

# --------------------- Utility and miscallaneous

shortner:
  url: 'http://roa.st/api.php'
