owner: 'nickname'
botpass: ''

channels:
  - '#mainroom':
      primary: True
      command: True
      speak: True
      spy: False
  - '#otherroom':
      command: True
      speak: True
      spy: False

# Simple api keys
apis:
  weather: ''
  wordnik: ''
  fml: ''
  wolfram: ''

meetup:
  location: ''
  notify: []
  day: ''

twitter:
  user: ''
  password: ''
  page: ''
  consumerkey: ''
  consumersecret: ''
  accesstoken: ''
  accesssecret: ''

# move to the db?
# safenumbers:
