owner: 'nickname'
botpass: ''

channels:
  - '#mainroom':
      primary: True
      command: True
      speak: True
      spy: False
  - '#otherroom':
      command: True
      speak: True
      spy: False

http:
    user: ''
    password: ''

meetup:
  location: ''
  notify: []
  day: ''

# Simple api keys
apis:
  weather: ''
  wordnik: ''
  fml: ''
  wolfram: ''

# My personal standard practice for
# setting up a new web presence is
# to setup a google account and base
# all the other accounts off that,
# hence the automatic inclusion of 
# the google account as the user
# for other applications. -HW
google:
  user: ''
  password: ''

facebook: ''
  user: "{google.user}@gmail.com"
  password: ''
  page: ''
  appid: ''
  secret: ''

twitter:
  user: "{google.user}@gmail.com"
  password: ''
  page: ''
  consumerkey: ''
  consumersecret: ''
  accesstoken: ''
  accesssecret: ''

marvel:
  publickey: ''
  privatekey: ''

github:
  clientid: ''
  clientsecret: ''
  token: ''

reddit:
  appid: ''
  secret: ''

delicious:
  user: ''
  pass: ''

twilio:
  sid: ''
  token: ''
  number: ''


# move to the db?
# safenumbers:
