owner: sublimnl

channels:
  '#okdrink_34234234':
    primary: True
    command: True
    speak: True
    spy: False
    intro: |
      Long, long ago, erikbeta went on vacation from OkCupid, and melanarchy messaged chiyou to say: "Fuck. Who am I going to bitch to all day?" to which chiyou replied "inorite?" and much bitching was done. Upon erikbeta's return, #jailbait was created, as a place to continue the bitching and trade pictures of obviously underage users.
      After the great OkExodus of 2010, our numbers did swell with Euj1, kenfree, realvinay, dcross2, digx, and woxidu, all dissaffected and enraged, except for woxidu, who was weirdly content at OkCupid, so we kind of slinked away into #okdrink to continue our 18 month recovery process of spewing vitriol and libel at the founders of OkCupid.
      Once this wound down and erikbeta quit, woxidu was brought back to the fold and there was much rejoicing. jsbronder came too. He does fancy linux shit. So chiyou moved on to AdCloud, which became AdCirrus when George ruined the company's brand by bilking a client for 8k and the client wrote about it (http://www.inspiredstartup.com/adcloudmedia/).
      jcb bailed early from the debacle, and once George stopped paying chiyou, chiyou sued him and we took to calling the company AdVapor, since they didn't appear to produce anything useful. They did have a really hot chick there, and entertaining names in the sales department, including Brittany Tingle and Guy Baretta. At some point, digx brought Viza on board.
      chiyou's ad serving career ended shortly thereafter at the managerial apocalypse known as Mojiva, or Mocean, depending on who you asked. The mocean of the otion was at such a level of mindless fuckery that castr0 and loxo33 bailed shortly after arriving, and they too were brought among the saved, amen.
      Now our ranks swell again with sublimnl, xitrium, and arach_, as lot18 shifts its business strategy from slow burn to nose dive, and we can all look forward to the growing web of seriously connected people distributed across the continental tech scene in various mid-level development positions. Someday, we shall use our powers for evil, and the world probably won't notice, but it will be cool. No girls allowed.
  '#SalsaBot':
    command: True
    speak: True
    spy: False
    intro: |
      this is a multiline
      string that is something
      something idk what

