researcher:
    wordnik_api_url: !env WORDNIK_API_URL
    wordnik_api_key: !env WORDNIK_API_KEY
    google_search_key: !env GOOGLE_SEARCH_KEY
    google_search_id: !env GOOGLE_SEARCH_ID

publicist:
    twitter_link: 'https://twitter.com/BotMongo'
    twitter_consumer_key: !env TWITTER_CONSUMER_KEY
    twitter_consumer_secret: !env TWITTER_CONSUMER_SECRET
    twitter_access_token: !env TWITTER_ACCESS_TOKEN
    twitter_access_secret: !env TWITTER_ACCESS_SECRET
