# Webserver
website:
  url: 'http://mongobot.com'
  reload: '/tmp/mongo.reload'

  # Server media diretories
  serverstorage: 'server/static'
  gifs: "{directory.serverstorage}/gifs"
  thumbs: "{directory.serverstorage}/thumbs"


